### ISSUE TITLE
Z-Fighting occurs in the 3D viewport

### ISSUE THREAD

**Issue by NukemD** [LogicAndTrick/sledge#197]
If the 3D viewport camera is far enough from a very thin brush flush against another brush behind it, Z-Fighting will occur. The closest textured face will be corrupted with the textured face behind it, very much like the Z-Fighting issue in the old WON version of Half-life.

Z-Fighting also occurs where two or more brush faces of any size touch.

![zfight](https://cloud.githubusercontent.com/assets/1351169/4658712/c1ebc5e0-5502-11e4-9eed-3053cdeba6a0.jpg)

**Comment by JamesK89** [comment]
After digging around in some of the graphics code Sledge seems to default to a hardcoded 24-bit depth buffer. I'm not really sure there is much that can be done on Sledge's side since, if I am not mistaken, we'd still need room for a stencil buffer and devices and drivers that support buffers larger than 32-bit can be hit or miss (24-bit z-buffer and 8-bit stencil are the most common buffer sizes used in commercial games) so we'd have to resort to some funky detection methods on the off chance that the end user has a device and driver that supports larger buffers. Alternatively one option we might be able to do is let the user choose their depth buffer size from a dropdown in the option dialog and let them suffer the consequences.

**Comment by NukemD** [comment]
If other map editors can make it work, I don't see any reason why Sledge can't.

I don't know why you'd need a depth buffer higher than 32 bits considering that the Z buffer, stencil buffer and regular rendering buffer are all located in different places in video memory.

**Comment by LogicAndTrick** [comment]
Thanks for pointing out that this was a depth buffer issue. As obvious as it sounds, I hadn't made the connection. I've been reading up on depth buffers and it looks like I've been making a few pretty fundamental mistakes when it comes to the depth buffer.

According to [this website](http://www.sjbaker.org/steve/omniv/love_your_z_buffer.html), the value of the near plane is incredibly influential on the depth buffer. Sledge currently uses `0.1` for the near clipping plane, but simply increasing that to `1.0` increases the accuracy of the depth buffer by a factor of 10 without really any significant penalties.

Considering this, I think we can resolve this issue by making this simple change in `Sledge.UI.Viewport3D`:

```csharp
public override Matrix4 GetViewportMatrix()
{
    const float near = 1.0f; // was 0.1f
    var ratio = Width / (float)Height;
    if (ratio <= 0) ratio = 1;
    return Matrix4.CreatePerspectiveFieldOfView(MathHelper.DegreesToRadians(Camera.FOV), ratio, near, Camera.ClipDistance);
}
```

I also like the idea of making the depth buffer precision configurable, though I need to do some research on what happens if you request a 32-bit buffer on a system that doesn't support it (does it just use 24-bit instead, does it crash, etc). There are also some [more advanced depth buffer implementations](http://outerra.blogspot.com.au/2012/11/maximizing-depth-buffer-range-and.html) that can be done in shaders, but I would like to avoid that for the time being.

**Comment by JamesK89** [comment]
I never even thought about the nearest frustum plane causing it even though I have observed strange behavior with sub-1.0 near planes in OpenGL before. I've been doing some Googling and can't find much information on querying the driver/hardware capabilities like you can with DirectX. If we were on Linux I would just pipe information from glxinfo to find out but alas we are not. What we might do in a worst case scenario is allow the user to choose between 16 bit (actually 24 bit; 16 bit depth and 8 bit stencil) and 24 bit (actually 32 bit, the most common; 24 bit depth and 8 bit stencil) and warn them with a modal dialog that it might cause serious problems if their hardware does not support it. An 8 bit option is imaginably out of the question as I can't imagine 8 bit being all that useful even if the environment for some reason does support it and we'd still need space for the stencil. I'm actually assuming we're using a stencil buffer here or will in the future but if there is no reason to have a stencil buffer then we can have even more space for a depth buffer.

**Comment by LogicAndTrick** [comment]
I don't think there'll be a need for a stencil buffer, if I ever add shadows to the renderer, they'll just be low-resolution shadow maps using textures. That opens up the option for 32 bit depth buffers without much hassle (there is a `GL_DEPTH32F_STENCIL8​` image format, however I can't find much information on it).

**Comment by JamesK89** [comment]
I don't want to get too off track from the depth buffer issue but one case I can make (I am not trying to be argumentative by the way) for keeping a stencil buffer is if we want to implement a deferred rendering mode which if I recall correctly requires a stencil buffer. This would enable loosely previewing lights (I say loosely because aside from Alien Swarm both GoldSrc and Source do not natively support deferred lighting), including the environment sun light, in real time similar to the Source Hammer editor's "3D Lighting Preview" mode. I suppose you could use low-res dynamically generated shadow maps as you mentioned but given the type of calculations involved it *might* be faster to use a deferred rendering pipeline especially given how small the viewport usually is. I feel the deferred shading discussion would warrant a separate GitHub issue by itself but I wanted to make a quick case for not throwing out the stencil buffer in the context of the depth buffer issue.

**Comment by LogicAndTrick** [comment]
I'm not opposed either way, it's pretty easy to switch in whichever buffers are needed anyway. I looked at a few different shadowing techniques a while ago and concluded that shadow maps are the most straight-forward (I've not done shadows before), but if deferred lighting is (relatively) easy too, I'd definitely be interested in using that instead. As you said, neither engine's lighting model can be emulated since it's dependent on the compile tools, so either implementation is fine.

I'm going to stick with the 24-bit depth buffer for the current work I'm doing on the scene rendering engine, once that's done we can take a look at options with lighting and shadows. Performance is the most important thing (at small and large resolutions), but how nice it looks and how maintainable the code is should also be considered.

**Comment by NukemD** [comment]
Hammers' "3D light preview" mode is so awful and inaccurate that it's useless. In the rare case it doesn't cause Hammer to crash, it only does a single ray trace from a light or light_spot entity in a limited radius. It doesn't at all attempt to calculate light_environment or texture lights.

**Comment by LogicAndTrick** [comment]
Closing this issue out as I believe it's not an issue in the new DirectX renderer which is using a 32 bit depth buffer.
