### ISSUE TITLE
Multi-platform Support for Linux, OSX, and Windows.

### ISSUE THREAD

**Issue by dark-c0de** [LogicAndTrick/sledge#217]
Hello!

I was able to successfully clone and build sledge using xamarin studio on the mac. It build successfully, and even started up. Sadly, it crashes shortly after startup.

It would be awesome if someone could make sledge compile and run through xamarin or monodevelop. This would allow sledge to run on any OS, which would make sledge's user base skyrocket.

What do you think?

**Comment by LogicAndTrick** [comment]
It'd be nice, but unfortunately I've given up on trying to get cross-platform support.

Mono doesn't support Windows forms, so it would require a rewrite of the entire UI. I put a lot of time into trying to get GTK working, but I was blocked because cross platform OpenGL using GTK does doesn't seem possible. It's not something I plan to spend more time on until there are solid Qt bindings for .NET.

**Comment by dark-c0de** [comment]
Maybe take a look into https://www.wxwidgets.org/ instead of GTK.

Also, with VS 2015 there is apparently native .net core which allows .NET to run nativity on OSX, Linux, and Windows.

**Comment by JamesK89** [comment]
@dark-c0de wxWidgets is an awesome library but unfortunately the wx.NET library is grossly out of date and no longer being maintained so consequently I wouldn't consider it worthwhile since we would essentially have to take up maintaining wx.NET in addition to Sledge.

**Comment by dark-c0de** [comment]
Not sure why you think it's not maintained or out of date, it was last updated 2 days ago.

**Comment by JamesK89** [comment]
@dark-c0de That is the wxWidgets C++ library itself. To use it we'd need some kind of interoperability library to use it from C# which in this case would be wx.NET, which is the library I mentioned that is out of date and unmaintained; http://wxnet.sourceforge.net/

Since the wxWidgets project makes mention of the wx.NET library I'm doubtful wxWidgets has built-in support for .NET.

**Comment by fdpierson** [comment]
GTK+ 3.16 came out a while back and contains a new widget called GtkGLArea. Hopefully, all you would need to do is compile this version of GTK+ for Windows and wire it up with GTK#, which does not support it as of now.

http://www.phoronix.com/scan.php?page=news_item&px=MTgxMjg

**Comment by LogicAndTrick** [comment]
Interesting, Sledge supports both pipelines so it wouldn't be difficult in that regard. I'll wait until it gets proper support in the GTK# project before looking into it though.

Even then, it would still require a complete UI rewrite, and considering that the target audience of VHE and Sledge is pretty much exclusively Windows-based, I can't justify the effort at this point. Support for Source is more important to me at the moment.

**Comment by dark-c0de** [comment]
Support for Linux and OSX was the entire reason I started looking for a hammer alternative, that's what brought me to Sledge. 

Sadly, Sledge is no better than hammer in that regard. You could potentially get thousands of new users and supporters for Sledge if it went multi-platform. 

Source games run on OSX, Linux, and Windows. Hammer only runs on Windows... :'(.

**Comment by LogicAndTrick** [comment]
That's fair, and I still hope to support other platforms in the future. However right now, my focus is getting a stable editor running on Windows.

In the `model-viewer` branch, I tried to do a massive switch to a new UI platform all in one go. That was a mistake, because I overreached and failed pretty hard. This time I'm going to slowly evolve the code so that it can be more UI-agnostic. At some point, that will make it much easier to get the code running on a different UI. But that's a long-term goal, so it'll take a while to get to that point.

I've already started the first step of this in the `rendering-impl` branch. I'm shifting all the rendering code into a separate library, which allows for switching of graphics engines. That removes the hard dependency on OpenGL and the OpenTK library, which means I can support DirectX in the future, or other graphics wrappers that might not be compatible with OpenTK (maybe gtk/opengl, monomac, Metal on OSX, Vulkan, etc.)

**Comment by fdpierson** [comment]
I came in with the assumption that you might use Gtk# as a multi-platform solution. Then I realized you could use different solutions for each platform, such as Gtk# for Linux, WinForms for Windows, and whatever they use for OSX!

Knowing this, setting up GtkGLArea for use with Gtk# would be dead simple, as Linux already has the latest versions of Gtk+ compiled. If you read the code, all Gtk# does is P/Invoke the Gtk+ library and wrap it up, so I would just have to add a few P/Invokes of my own and do some marshalling.

Do continue with whatever priorities you consider the highest, but I'm just laying out some ideas.

**Comment by LogicAndTrick** [comment]
Yeah, that's the plan. Linux is (relatively) straight-forward because GTK+ is well-supported. Getting a Mac version going is difficult though, because I can't afford to buy Mac hardware just to develop Sledge, and writing code in a virtual machine is simply not realistic.

**Comment by dark-c0de** [comment]
I've got a Mac and would be happy to support the OSX version.

**Comment by LogicAndTrick** [comment]
Unfortunately closing this as part of #238. The cross-platform story with .NET on the desktop is in a very sad state, especially once you add OpenGL into the mix. It's not realistic for me to support it. Sledge will remain Windows-only.
