### ISSUE TITLE
Some weird stuff going on

### ISSUE THREAD

**Issue by mrartuka** [LogicAndTrick/sledge#230]
Ok so yesterday(my time) there was small update to Source SDK,don't knwo what they changed exactly but now my map wont work,it have strange shadows all over textures.

2nd thing is that Sledge gives me error about "Multiple faces with same ID", those errors i never got in Hammer.
3rd thing is again about errors,Sledge says "Invalid Solid" for 50% of map,while Hammer didnt report any error,and map was working fine.

Today again some weird things happening, FGD files (default for cs go) are now rejected by Sledge,so textures,entity, all that doesn't work -_-

Sledge is great tool,i like how its fast with rendering in 3D view,but really i hate those small things that gives me error.

Also plase give us PREFAB option :(

**Comment by MASSIVELIVEFUN** [comment]
1) Strange shadows over textures.

If these shadows are rendering on your bsp geometry in the sledge editor you should check if your OpenGL drivers are up to date. I had the same issue and getting the latest release of these drivers helped me out.

2) Multiple faces with the same id.

No idea for a brute force solution for this issue. However I've been getting the same issue. You are not alone. In reality this is a non-issue since it doesn't royally screw over vmf files. At least from my experience it doesn't anyway.

3) Invalid solids for 50% of the map.

As long as your geometry isn't concave then you should be fine. Remember when in doubt, triangles never go wrong.

4) FGD files being rejected by Sledge.

Operation Wildfire was recently released for CSGO's 7th title update and they added more entities such as explosive barrels, self-stimshots, and wallhacking laser grenades reminiscent of CoD:AW seeker grenades.

(Yes they added laser wallhack grenades, if you don't believe me just google '3kliksphilip' and watch his summary of Operation Wildfire change logs and see them in action on de_dust2.)

Within the csgo fgd file they added these three entities and they put these items into the entity list around line 900 in the fgd file. However someone at valve misplaced the empty square brackets under each new entity header.

If you have notepad++, notepad, word pad, or any text editor you should be able to fix this issue just by observing from other lines where the brackets need to go to manually fix your issue.

ADDING TO THE WEIRD STUFF GOING ON:

- Sledge doesn't support displacements. So if you try to save a vmf file with a displacement on it the entire map will be deleted the next time you open the map. THANK BABY JESUS for the auto save feature.

- Opening a psuedo-Source sledge map in hammer will flag entities with the error of having an unused error parameter called spawnflag that has a default value of zero. Never messed with it, just had hammer auto remove the parameter from each entity with the alt+p method.

**Comment by LogicAndTrick** [comment]
Thanks for the info, but Source isn't supported yet, so you're going to have a lot of trouble trying to do any Source editing in Sledge for the time being. As mentioned there's no support for displacements, or other important Source features such as instances or entity I/O. Startup performance on Source is quite bad as well.

The invalid geometry may sometimes happen when opening .map and .vmf files because of the intersecting planes, Sledge has a different level of tolerance to VHE and I haven't worked out the best sensitivity level there. The invalid IDs is an interesting one, but I know what causes it and it should be fixable. The spawnflags key on entities should be harmless, but I'll make a note to remove it from the VMF output because VMF already has a dedicated key for the spawnflags.

Glad to hear Valve is up to their old tricks with invalid FGD files. Does VHE handle them correctly? I'll need to add a work-around for that format if VHE can open the file.

**Comment by MASSIVELIVEFUN** [comment]
Initially VHE was actually throwing error messages in its console about the csgo.fgd file. After fixing the brackets to where they should be both hammer and sledge were able to parse the file for use, so basically it's nothing to sweat over.

Also if you don't mind I've been lurking on the TWHL website, reading the forum post about Sledge, and how you self taught yourself to make this program, et cetera. Basically do you recommend any resources or online articles for understanding 3-D applications because I'd love to contribute to Sledge. It's just that I'm a complete newbie when it comes to programming, but I really want to get into the nitty gritty of all this impressive stuff. We all gotta start somewhere, right?

**Comment by mrartuka** [comment]
Tnx for replying guys.
Oh i found already that fix for csgo.fgd file -_- Didn't expect Valve developers to have such mistake.
This is surf map,so yeah its not like i have some weird shape stuff inside, but those shadows started after Source SDK update :( 
This happened after update: [http://imgur.com/YQAd98u](url) and this http://imgur.com/lcKtaNr

Also when save map in Sledge,and try to open in hammer,map gets broken ,all brushes are messed up.

**Comment by LogicAndTrick** [comment]
@mrartuka: The shadows are in-game? It's probably not a problem with Sledge, the compilers and so on are all from the SDK so I would blame something in there. I will experiment with the CSGO VHE and see if I can work out why it's not loading Sledge maps properly.

@MASSIVELIVEFUN: There's a lot of OpenGL tutorials out there, but http://learnopengl.com/ looks like one of the better ones that goes through 3D programming from the beginning. Getting into 3D programming can be very difficult so if you want to start on something easier try a higher level library such as [three.js](http://threejs.org/) or something similar for the programming language you want to use.

If you don't want to learn the backend OpenGL stuff there's still plenty of work in Sledge that doesn't need you to know OpenGL, but for most things you will need to be familiar with 3D concepts like vector and matrix operations. There's lots of sites that have resources on 3D mathematics, search on Google until you find one you like.

Let me know if that helps!

**Comment by LogicAndTrick** [comment]
Closing this issue out, Source support will be added some point, but Sledge won't handle Source maps yet.
