### ISSUE TITLE
Sledge Project Status

### ISSUE THREAD

**Issue by SourcePowered** [LogicAndTrick/sledge#237]
Please give us a definite answer, we do not want to do some unnecessary wait.

**Comment by LogicAndTrick** [comment]
Indefinitely postponed; so for all intents and purposes, yes.

**Comment by SourcePowered** [comment]
Why indefinitely postponed? :(

**Comment by LogicAndTrick** [comment]
It's a lot of things adding up, really. I don't really have the time or motivation to work on it, not many people use it anyway, the Jackhammer devs are more skilled than I am and they have a better product (even if it's not open source), the bugs are difficult to fix, and I'm bad at graphics programming. I would like to work on it but I just don't have the talent or knowledge to make the performance reasonable enough for it to be a useful program for Source. It works mostly fine for Goldsource though.

**Comment by fuzun** [comment]
@LogicAndTrick It would be good to see you in JackHammer's dev team.

**Comment by LogicAndTrick** [comment]
I'd be happy to work on it if it was open source, unfortunately I don't want to work on closed software.

**Comment by Pugsworth** [comment]
@LogicAndTrick I feel the biggest reason adoption rate isn't high is due to source support.
I know, personally, I would use Sledge over Hammer if it had Source support.
I've kinda been waiting for the first stable build of Source support.

I tried Jack and it just didn't feel like it was going down the same path as Sledge

**Comment by LogicAndTrick** [comment]
I think you're right. There's a decent number of options for HL1 editing, but for Source, Hammer is still the only decent option.

I'm not saying this project is completely dead, but I need a big break from it because it was seriously draining me. I would like to start working on it again at some point, or build Source editing functionality into an existing editor, so that there's at least one full-featured alternative to VHE for Source editing.

**Comment by JamesK89** [comment]
This project has too much merit to die. It is not only useful for the GoldSrc/Source engine community but also for the indie game dev community (in similar vein as Tiled is for 2D games) since it is free of all the licensing restrictions on the Hammer editor being only able to be used for Valve games. Unfortunately I've been too busy with other projects, and life, to contribute.

I totally get where LogicAndTrick is coming from and I have nothing less than respect and awe for this incredible tool he built.


Just my two cents.

**Comment by LogicAndTrick** [comment]
Howdy folks, so I've been thinking about what I can do to get back into this without overwhelming myself. I'm keen to get some progress on Sledge, but I made the scope too big for one person (or even a small group tbh) to maintain. So I'm going to start cutting out features until Sledge is a small (but still entirely functional!) editor.

First is to remove support for old platforms:

- Remove Windows XP support (it's not supported by MS anymore)
- Update to .NET 4.5 (so I can use the new async features to assist with performance improvements)
- Remove all support for OpenGL 1 (OpenGL 2 is more than 10 years old)

And stop chasing unrealistic goals:

- Stop all efforts in potentially targeting non-Windows platforms (just not happening with a Winforms app)
- Stop thinking about DirectX or other renderers (with the potential to allow plugin authors to create their own at some point)
- Stop adding features that go too far above and beyond VHE or other editors (for now)
- Finish the renderer rewrite (that's been going on for way too long) and stop trying to add crazy features

Then start optimising performance:

- Move to a more asynchronous programming model when loading dependencies
- Load as little as possible until the last second (texture providers are terrible right now)

Then I want to finally move onto Source support:

- Support for displacements
- Support for instances
- Add source compile tools
- (whatever else is needed...)

Finally, focus on something that's small and maintainable, but also flexible enough for people to add plugins:

- Add a plugin system
- Add a lot of plugin points
- Move all tools, commands, etc. into "bundled" plugins to ensure that plugins have full functionality
- Add a more flexible messaging system to allow components to talk to each other 

Any thoughts? I think this is the best way I can move forward on the project without it dying. If anybody wants support for the old platforms, they can use VHE, Jackhammer, or any of the many other HL1 editors that are available.

**Comment by Krusing** [comment]
Cutting off unnecessary support for older platforms and focusing on one single system is a good decision. I have been looking forward to this for two years and it is great to see the ball rolling again. You have my respect!

**Comment by Pugsworth** [comment]
I completely agree with the reduction.
- What possible need is there for Windows XP support anymore?
- Is there a legitimate reason why 90% of people don't have .NET 4.5 (besides business/schools)? .NET 4.5 was released nearly 5 years ago.
- The first commercial Source game was in 2004, only slightly older than OpenGL 2.0. Honestly, who is really rocking a card that doesn't hit at most OpenGL 2.0?

Most other things are features and enhancements that can always come later.

**Comment by LogicAndTrick** [comment]
Thanks for the feedback guys, I've been starting work on this but things will probably be quiet for a while because I'm doing some pretty major changes in some places and I've broken quite a few things. My first goal is to improve texture loading because that's a major pain point in Source (right now it takes > 1 minute to load all the textures for TF2, the changes I'm making should bring it down to < 5 seconds)

**Comment by LavenderMoon** [comment]
Just don't drop .pk3 texture support in your rewrite. :rofl: Seriously, though, down the line someone else will add cross-platform support, once the editor is in a more polished state. :+1:

**Comment by LogicAndTrick** [comment]
I don't think I'll drop pk3 support, but I might think about making it load the proper shaders rather than just using the base images. Though I might leave it until that can be extracted into a plugin, because my primary target is HL1 and Source.

**Comment by LavenderMoon** [comment]
Definitely, getting the shaders working for .pk3 files is low priority. Especially since I haven't even sent in a pull request for Quake 3 map generation support yet. I have used Sledge to make Quake 3 maps, but I didn't properly add support for it to Sledge.

**Comment by JamesK89** [comment]
As regard to the objective of simplification I was thinking maybe the goal should be to abstract the core of Sledge from the UI as much as possible. This way you can focus on your goals and the Windows implementation without sacrificing multi-platform support in the future.

**Comment by LogicAndTrick** [comment]
Abstraction away from the UI will definitely come, but it'll be with plugins and extensibility in mind, rather than multi-platform. If it's easy and convenient I'll do it, but worrying about multi-platform is what burned me out in the first place, and I'm not going to spend too much time on it.

Desktop apps with .NET aren't in a very good place at the moment, and I'm not sure they ever will be once you add OpenGL into the equation. I'm not opposed to supporting other platforms in theory, but I am opposed to spending too much time on it when I have more important things to focus on.

**Comment by fuzun** [comment]
Requst: Workaround for displacements in goldsrc. This is my dream :/

**Comment by fuzun** [comment]
And Xash3d support if possible. Maybe displacement, etc. implementation would be possible this way.

**Comment by LogicAndTrick** [comment]
Source displacements will also work in Goldsource, yeah. When you compile a HL1 map that has displacements, it will convert them into brushwork.

**Comment by LavenderMoon** [comment]
@fuzun How would Xash3D support differ from GoldSrc support?

**Comment by SourcePowered** [comment]
@LavenderMoon Because Xash3D Engine is more and more far from GoldSrc. Better to say it's completely independent, and it is no more connection with GoldSrc.
@fuzun I don't think it's possible to support Xash3D, and I don't recommend supporting Xash3D. Because Xash3D had JackHammer, that's enough. And Xash3D is not released by the Valve, and the difference between the GoldSrc, support it, equivalent to support a new engine, no need. We only do GoldSrc and Source, others are not considered.

**Comment by ciba43** [comment]
Xash is literally hacked-together, reverse engineered GoldSource. Pretty much everything is the same, the last time I checked. While there are special entities, they don't need much work, a proper fgd is fine (which is also provided by the Xash's author).

**Comment by LavenderMoon** [comment]
@SourcePowered Isn't Xash3D's goal literally backwards-compatibility with the GoldSrc engine's assets and mods?

**Comment by SourcePowered** [comment]
You can read the latest version of the code, getting farther and farther away.

**Comment by ciba43** [comment]
The author stated that the goal is for the Xash3d engine to be completely compatible with Goldsource. He also stated (on the russian forums) that he wants to focus working on a new engine XashNT, which will for most part drop GoldSource support and focus on improving the features even further. Although, the post about that was from ~2014, I guess it's still relevant. Other than that, Xash3D is pretty much identical with GoldSource.

**Comment by SourcePowered** [comment]
YES, but the important thing is, we don't like someone, maybe you know about that. I'm sorry.

**Comment by LogicAndTrick** [comment]
I don't know much about Xash so I have no plans on doing anything special to support it. Once it's in there, the plugin system should hopefully make it possible to add any custom functionality it might need.

**Comment by LavenderMoon** [comment]
@SourcePowered, I can't understand what you're saying. Who is "we", and who
is "someone"?

**Comment by SourcePowered** [comment]
@LavenderMoon I just want to convey the meaning of some people, I really do not want @ him.

**Comment by SourcePowered** [comment]
Since the Issues has no objection, then we'll close it. Thank you for your positive response and cooperation.
